dist: bionic

language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - source setup.sh
  - coverage run --source=nala -p setup.py test
  - make test-c SANITIZE=yes
  - PYTHONPATH=. coverage run --source=nala -p -m nala init my-suite
  - coverage combine .coverage.*
  - make -C my-suite NALA="PYTHONPATH=.. python3 -m nala"

after_success:
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
  - coveralls
