language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=nala setup.py test
  - make test-c NALA="PYTHONPATH=../.. coverage run --source=nala -m nala"

after_success:
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
  - coveralls
